### ISSUE TITLE
参见对正在编译的函数 模板 实例化

### ISSUE THREAD

**Issue by IULOVE** [loveyacper/ananas#2]
note: 参见对正在编译的函数 模板 实例化“ananas::Future<int> ananas::Future<int>::_ThenImpl<F,R,T&&>(ananas::Scheduler *,F &&,ananas::internal::ResultOfWrapper<F,T &&>)”的引用
1>        with
1>        [
1>            F=main::<lambda_0ca2531bee9689aededc86c496028799>,
1>            R=ananas::internal::CallableResult<main::<lambda_0ca2531bee9689aededc86c496028799>,int>,
1>            T=int
1>        ]

我用msvc编译提示这个，但是能编译过去的，警告降到2级就不会提示···有问题吗这个！

**Comment by loveyacper** [comment]
你好，ananas只支持linux和macos，也就是gcc和clang，没有尝试过windows编译。另外这里出错信息提示不全，也可以提供以下msvc的版本。

**Comment by loveyacper** [comment]
可能需要你截取完整的警告信息看一下，以及代码。在clang和gcc -Wall并没有遇到警告。

**Comment by IULOVE** [comment]
好吧·其实不是警告也不是错误是 note就是编译的时候会提示这个信息
![qq 20190126153640](https://user-images.githubusercontent.com/14193276/51784216-59f0e200-2180-11e9-9f31-99d4cfe91877.png) 只要调用了 .the 实例化_ThenImpl 都会有提示··我只会用win··c++也不行！

**Comment by loveyacper** [comment]
嗯，我先看下，c++语法也是不熟，全靠编译器提示，写出准确的代码:-)
不过这个示例，在clang和gcc的-Wall都是没告警的，可能告警级别没有msvc严格。

**Comment by loveyacper** [comment]
另外建议网上搜一下“参见对正在编译的函数 模板 实例化”，看看有什么解决方案
更高阶一点，google搜索对应的英文，SO上应该会有帮助。
